#!/bin/bash
export PROJECT_DIR="$HOME/conserved_site_project"
export VINA="/opt/homebrew/bin/vina"
export PYMOL="/opt/homebrew/bin/pymol"
export MAFFT="/opt/homebrew/bin/mafft"
export OBABEL="$PROJECT_DIR/.venv/bin/obabel"
# Phase 6 (Modeller homology modelling)
export MODELLER_HOME="/Library/modeller-10.8"
export MODELLER_PYBIND="$MODELLER_HOME/lib/mac10v4/python3.8"
export MODELLER_MODLIB="$MODELLER_HOME/modlib"
export PYTHONPATH="$MODELLER_MODLIB:$MODELLER_PYBIND:${PYTHONPATH:-}"
export KEY_MODELLER="MODELIRANJE"
export CLUSTALW="/opt/homebrew/bin/clustalw"
export BLASTP="/opt/homebrew/bin/blastp"
source "$PROJECT_DIR/.venv/bin/activate"
